
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ADD MULT NUM SUB\nS : Exp\n\nExp : Exp ADD Termo\n\nExp : Exp SUB Termo\n\nExp : Termo\n\nTermo : Termo MULT Factor\n\nTermo : Factor\n\nFactor : NUM\n'
    
_lr_action_items = {'NUM':([0,6,7,8,],[5,5,5,5,]),'$end':([1,2,3,4,5,9,10,11,],[0,-1,-4,-6,-7,-2,-3,-5,]),'ADD':([2,3,4,5,9,10,11,],[6,-4,-6,-7,-2,-3,-5,]),'SUB':([2,3,4,5,9,10,11,],[7,-4,-6,-7,-2,-3,-5,]),'MULT':([3,4,5,9,10,11,],[8,-6,-7,8,8,-5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'S':([0,],[1,]),'Exp':([0,],[2,]),'Termo':([0,6,7,],[3,9,10,]),'Factor':([0,6,7,8,],[4,4,4,11,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> S","S'",1,None,None,None),
  ('S -> Exp','S',1,'p_global','exp_sin.py',6),
  ('Exp -> Exp ADD Termo','Exp',3,'p_exp_add','exp_sin.py',12),
  ('Exp -> Exp SUB Termo','Exp',3,'p_exp_sub','exp_sin.py',19),
  ('Exp -> Termo','Exp',1,'p_exp_term','exp_sin.py',26),
  ('Termo -> Termo MULT Factor','Termo',3,'p_term_mult','exp_sin.py',33),
  ('Termo -> Factor','Termo',1,'p_term_factor','exp_sin.py',40),
  ('Factor -> NUM','Factor',1,'p_factor_num','exp_sin.py',47),
]
